## static_territories
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='2' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='9' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='19' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='142' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='150' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='30' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='35' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='143' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='145' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='39' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='151' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='154' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='155' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='5' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='13' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='21' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='29' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='11' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='14' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='15' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='17' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='18' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='53' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='54' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='57' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='61' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_fa='',tr_iso_nr='34' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_fa='آندورا' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_fa='امارات متحدهٔ عربی' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_fa='افغانستان' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_fa='آنتیگوا و باربودا' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_fa='آنگویلا' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_fa='آلبانی' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_fa='ارمنستان' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_fa='آنگولا' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_fa='جنوبگان' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_fa='آرژانتین' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_fa='ساموآی آمریکا' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_fa='اتریش' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_fa='استرالیا' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_fa='آروبا' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_fa='جمهوری آذربایجان' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_fa='بوسنی و هرزگوین' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_fa='باربادوس' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_fa='بنگلادش' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_fa='بلژیک' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_fa='بورکینافاسو' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_fa='بلغارستان' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_fa='بحرین' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_fa='بوروندی' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_fa='بنین' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_fa='برمودا' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_fa='برونئی' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_fa='بولیوی' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_fa='برزیل' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_fa='باهاما' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_fa='بوتان' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_fa='جزیره بووه' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_fa='بوتسوانا' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_fa='بلاروس' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_fa='بلیز' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_fa='کانادا' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_fa='جزایر کوکوس (کیلینگ)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_fa='کنگو (جمهوری دموکراتیک)' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_fa='جمهوری افریقای مرکزی' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_fa='کنگو (جمهوری)' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_fa='سوئیس' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_fa='ساحل عاج' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_fa='جزایر کوک' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_fa='شیلی' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_fa='کامرون' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_fa='چین' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_fa='کلمبیا' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_fa='کاستاریکا' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_fa='کوبا' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_fa='کیپ‌ورد' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_fa='جزیرهٔ کریسمس' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_fa='قبرس' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_fa='جمهوری چک' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_fa='آلمان' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_fa='جیبوتی' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_fa='دانمارک' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_fa='دومینیکا' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_fa='جمهوری دومینیکن' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_fa='الجزایر' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_fa='اکوادور' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_fa='استونی' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_fa='مصر' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_fa='صحرای غربی' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_fa='اریتره' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_fa='اسپانیا' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_fa='اتیوپی' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_fa='فنلاند' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_fa='فیجی' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_fa='جزایر فالکلند (ایسلاس مالویناس)' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_fa='میکرونزی' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_fa='جزایر فارو' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_fa='فرانسه' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_fa='گابن' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_fa='بریتانیا' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_fa='گرنادا' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_fa='گرجستان' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_fa='گویان فرانسه' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_fa='غنا' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_fa='جبل‌الطارق' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_fa='گرینلند' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_fa='گامبیا' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_fa='گینه' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_fa='گوادلوپ' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_fa='گینهٔ استوایی' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_fa='یونان' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_fa='جزایر جورجیای جنوبی و ساندویچ جنوبی' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_fa='گواتمالا' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_fa='گوام' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_fa='گینهٔ بیسائو' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_fa='گویان' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_fa='هنگ‌کنگ' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_fa='هندوراس' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_fa='کرواسی' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_fa='هائیتی' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_fa='مجارستان' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_fa='اندونزی' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_fa='ایرلند' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_fa='اسرائیل' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_fa='هند' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_fa='قلمرو بریتانیا در اقیانوس هند' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_fa='عراق' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_fa='ایران' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_fa='ایسلند' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_fa='ایتالیا' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_fa='جامائیکا' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_fa='اردن' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_fa='ژاپن' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_fa='کنیا' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_fa='قرقیزستان' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_fa='کامبوج' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_fa='کیریباتی' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_fa='کومور' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_fa='سنت کیتس و نویس' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_fa='کرهٔ شمالی' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_fa='کرهٔ جنوبی' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_fa='کویت' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_fa='جزایر کیمنن' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_fa='قزاقستان' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_fa='لائوس' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_fa='لبنان' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_fa='سنت لوسیا' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_fa='لیختن‌اشتاین' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_fa='سری‌لانکا' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_fa='لیبریا' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_fa='لسوتو' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_fa='لیتوانی' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_fa='لوکزامبورگ' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_fa='لتونی' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_fa='لیبی' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_fa='مراکش' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_fa='موناکو' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_fa='مولداوی' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_fa='ماداگاسکار' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_fa='جزایر مارشال' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_fa='مقدونیه (جمهوری سابقاً یوگسلاو)' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_fa='مالی' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_fa='میانمار (برمه)' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_fa='مغولستان' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_fa='ماکائو، منطقه اداری خاص چینو' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_fa='جزایر ماریانای شمالی' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_fa='مارتینیک' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_fa='موریتانی' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_fa='مونت‌سرات' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_fa='مالت' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_fa='موریس' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_fa='مالدیو' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_fa='مالاوی' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_fa='مکزیک' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_fa='مالزی' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_fa='موزامبیک' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_fa='نامیبیا' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_fa='کالدونیای جدید' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_fa='نیجر' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_fa='جزیره نورفک' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_fa='نیجریه' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_fa='نیکاراگوئه' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_fa='هلند' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_fa='نروژ' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_fa='نپال' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_fa='نائورو' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_fa='نیوئه' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_fa='زلاند نو' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_fa='عمان' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_fa='پاناما' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_fa='پرو' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_fa='پلی‌نزی فرانسه' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_fa='پاپوا گینهٔ نو' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_fa='فیلیپین' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_fa='پاکستان' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_fa='لهستان' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_fa='سن-پیر-ا-میکلون' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_fa='جزایر پیت‌کرن' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_fa='پورتوریکو' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_fa='پرتغال' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_fa='پالائو' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_fa='پاراگوئه' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_fa='قطر' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_fa='رئونیون' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_fa='رومانی' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_fa='روسیه' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_fa='رواندا' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_fa='عربستان' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_fa='جزایر سلیمان' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_fa='سیشل' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_fa='سودان' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_fa='سوئد' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_fa='سنگاپور' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_fa='سنت هلن' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_fa='اسلوونی' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_fa='اسوالبارد و جان‌ماین' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_fa='اسلواکی' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_fa='سیرالئون' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_fa='سن مارینو' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_fa='سنگال' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_fa='سومالی' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_fa='سورینام' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_fa='سائوتومه و پرینسیپ' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_fa='السالوادور' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_fa='سوریه' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_fa='سوازیلند' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_fa='جزایر تورکس و کایکوس' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_fa='چاد' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_fa='مستعمره‌های جنوبی فرانسه' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_fa='توگو' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_fa='تایلند' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_fa='تاجیکستان' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_fa='توکلائو' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_fa='ترکمنستان' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_fa='تونس' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_fa='تونگا' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_fa='تیمور شرقی' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_fa='ترکیه' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_fa='ترینیداد و توباگو' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_fa='تووالو' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_fa='تایوان' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_fa='تانزانیا' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_fa='اوکراین' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_fa='اوگاندا' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_fa='جزایر دورافتادهٔ ایالات متحده' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_fa='ایالات متحدهٔ امریکا' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_fa='اروگوئه' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_fa='ازبکستان' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_fa='واتیکان' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_fa='سنت وینسنت و گرنادین‌ها' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_fa='ونزوئلا' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_fa='جزایر ویرجین بریتانیا' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_fa='جزایر ویرجین ایالات متحده' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_fa='ویتنام' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_fa='وانواتو' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_fa='والیس و فوتونا' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_fa='ساموآ' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_fa='یمن' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_fa='مایوت' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_fa='افریقای جنوبی' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_fa='زامبیا' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_fa='زیمبابوه' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_fa='فلسطین' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_fa='جزایر اُلند' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_fa='جزیرهٔ هرد و جزایر مک‌دونالد' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_fa='مونته‌نگرو' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_fa='صربستان' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_fa='جرزی' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_fa='گرنزی' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_fa='جزیرهٔ من' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_fa='سنت مارتین' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_fa='سن بارتلمی' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_fa='جزایر کارائیب هلند' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_fa='کوراسائو' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_fa='سنت مارتن' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_fa='سودان جنوبی' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_fa='جزایر آسنسیون' WHERE cn_iso_2='AC';
UPDATE static_countries SET cn_short_fa='آنتیل هلند' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_fa='جزایر کلیپرتون' WHERE cn_iso_2='CP';
UPDATE static_countries SET cn_short_fa='دیه‌گو گارسیا' WHERE cn_iso_2='DG';
UPDATE static_countries SET cn_short_fa='سبته و ملیله' WHERE cn_iso_2='EA';
UPDATE static_countries SET cn_short_fa='اتحادیهٔ اروپا' WHERE cn_iso_2='EU';
UPDATE static_countries SET cn_short_fa='جزایر قناری' WHERE cn_iso_2='IC';
UPDATE static_countries SET cn_short_fa='بخش‌های دورافتادهٔ اقیانوسیه' WHERE cn_iso_2='QO';
UPDATE static_countries SET cn_short_fa='تریستان دا کونا' WHERE cn_iso_2='TA';
UPDATE static_countries SET cn_short_fa='کوزووو' WHERE cn_iso_2='XK';
UPDATE static_countries SET cn_short_fa='ناحیهٔ نامشخص' WHERE cn_iso_2='ZZ';
UPDATE static_countries SET cn_short_fa='صربستان و مونته نگروص' WHERE cn_iso_2='CS';


## static_country_zones


## static_currencies
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AED' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ALL' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AMD' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ANG' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AOA' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ARS' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AUD' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AWG' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AZN' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BAM' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BBD' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BDT' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BGN' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BHD' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BIF' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BMD' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BND' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BOB' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BRL' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BSD' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BTN' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BWP' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BYR' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='BZD' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CAD' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CDF' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CHF' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CLP' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CNY' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='COP' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CRC' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CUP' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CVE' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CYP' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='CZK' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='DJF' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='DKK' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='DOP' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='DZD' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='EEK' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='EGP' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ERN' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ETB' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='EUR' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='FJD' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='FKP' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GBP' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GEL' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GHC' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GIP' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GMD' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GNF' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GTQ' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GWP' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='GYD' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='HKD' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='HNL' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='HRK' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='HTG' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='HUF' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='IDR' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ILS' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='INR' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='IQD' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='IRR' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ISK' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='JMD' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='JOD' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='JPY' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KES' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KGS' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KHR' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KMF' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KPW' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KRW' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KWD' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KYD' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='KZT' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LAK' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LBP' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LKR' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LRD' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LSL' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LTL' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LVL' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='LYD' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MAD' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MDL' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MKD' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MMK' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MNT' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MOP' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MRO' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MTL' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MUR' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MVR' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MWK' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MXN' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MYR' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MZM' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NAD' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NGN' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NIO' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NOK' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NPR' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='NZD' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='OMR' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PAB' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PEN' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PGK' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PHP' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PKR' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PLN' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='PYG' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='QAR' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ROL' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='RUB' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='RWF' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SAR' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SBD' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SCR' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SDG' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SEK' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SGD' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SHP' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SIT' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SKK' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SLL' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SOS' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='STD' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SVC' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SYP' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SZL' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='THB' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TJS' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TMM' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TND' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TOP' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TTD' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TWD' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TZS' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='UAH' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='UGX' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='USD' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='UYU' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='UZS' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='VEF' WHERE cu_iso_3='VEF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='VND' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='VUV' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='WST' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='XAF' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='XCD' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='XOF' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='XPF' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='YER' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ZAR' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ZMW' WHERE cu_iso_3='ZMW';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='ZWD' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='AFN' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='RSD' WHERE cu_iso_3='RSD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='MGA' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SRD' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='TRY' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_fa='',cu_sub_name_fa='',cu_iso_3='SSP' WHERE cu_iso_3='SSP';


## static_languages
UPDATE static_languages SET lg_name_fa='آبخازی',lg_iso_2='AB' WHERE lg_iso_2='AB';
UPDATE static_languages SET lg_name_fa='آفاری',lg_iso_2='AA' WHERE lg_iso_2='AA';
UPDATE static_languages SET lg_name_fa='آفریکانس',lg_iso_2='AF' WHERE lg_iso_2='AF';
UPDATE static_languages SET lg_name_fa='آلبانیایی',lg_iso_2='SQ' WHERE lg_iso_2='SQ';
UPDATE static_languages SET lg_name_fa='امهری',lg_iso_2='AM' WHERE lg_iso_2='AM';
UPDATE static_languages SET lg_name_fa='عربی',lg_iso_2='AR' WHERE lg_iso_2='AR';
UPDATE static_languages SET lg_name_fa='ارمنی',lg_iso_2='HY' WHERE lg_iso_2='HY';
UPDATE static_languages SET lg_name_fa='آسامی',lg_iso_2='AS' WHERE lg_iso_2='AS';
UPDATE static_languages SET lg_name_fa='آیمارایی',lg_iso_2='AY' WHERE lg_iso_2='AY';
UPDATE static_languages SET lg_name_fa='آذربایجانی',lg_iso_2='AZ' WHERE lg_iso_2='AZ';
UPDATE static_languages SET lg_name_fa='باشغیری',lg_iso_2='BA' WHERE lg_iso_2='BA';
UPDATE static_languages SET lg_name_fa='باسکی',lg_iso_2='EU' WHERE lg_iso_2='EU';
UPDATE static_languages SET lg_name_fa='بنگالی',lg_iso_2='BN' WHERE lg_iso_2='BN';
UPDATE static_languages SET lg_name_fa='جونخایی',lg_iso_2='DZ' WHERE lg_iso_2='DZ';
UPDATE static_languages SET lg_name_fa='بیهاری',lg_iso_2='BH' WHERE lg_iso_2='BH';
UPDATE static_languages SET lg_name_fa='بیسلاما',lg_iso_2='BI' WHERE lg_iso_2='BI';
UPDATE static_languages SET lg_name_fa='برتانیایی',lg_iso_2='BR' WHERE lg_iso_2='BR';
UPDATE static_languages SET lg_name_fa='بلغاری',lg_iso_2='BG' WHERE lg_iso_2='BG';
UPDATE static_languages SET lg_name_fa='برمه‌ای',lg_iso_2='MY' WHERE lg_iso_2='MY';
UPDATE static_languages SET lg_name_fa='بلوروسی',lg_iso_2='BE' WHERE lg_iso_2='BE';
UPDATE static_languages SET lg_name_fa='خمری',lg_iso_2='KM' WHERE lg_iso_2='KM';
UPDATE static_languages SET lg_name_fa='کاتالان',lg_iso_2='CA' WHERE lg_iso_2='CA';
UPDATE static_languages SET lg_name_fa='چوانگی',lg_iso_2='ZA' WHERE lg_iso_2='ZA';
UPDATE static_languages SET lg_name_fa='چینی',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_fa='کورسی',lg_iso_2='CO' WHERE lg_iso_2='CO';
UPDATE static_languages SET lg_name_fa='کروات',lg_iso_2='HR' WHERE lg_iso_2='HR';
UPDATE static_languages SET lg_name_fa='چکی',lg_iso_2='CS' WHERE lg_iso_2='CS';
UPDATE static_languages SET lg_name_fa='دانمارکی',lg_iso_2='DA' WHERE lg_iso_2='DA';
UPDATE static_languages SET lg_name_fa='هلندی',lg_iso_2='NL' WHERE lg_iso_2='NL';
UPDATE static_languages SET lg_name_fa='انگلیسی',lg_iso_2='EN' WHERE lg_iso_2='EN';
UPDATE static_languages SET lg_name_fa='اسپرانتو',lg_iso_2='EO' WHERE lg_iso_2='EO';
UPDATE static_languages SET lg_name_fa='استونیایی',lg_iso_2='ET' WHERE lg_iso_2='ET';
UPDATE static_languages SET lg_name_fa='فارویی',lg_iso_2='FO' WHERE lg_iso_2='FO';
UPDATE static_languages SET lg_name_fa='فارسی',lg_iso_2='FA' WHERE lg_iso_2='FA';
UPDATE static_languages SET lg_name_fa='فیجیایی',lg_iso_2='FJ' WHERE lg_iso_2='FJ';
UPDATE static_languages SET lg_name_fa='فنلاندی',lg_iso_2='FI' WHERE lg_iso_2='FI';
UPDATE static_languages SET lg_name_fa='فرانسوی',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_fa='فریزی غربی',lg_iso_2='FY' WHERE lg_iso_2='FY';
UPDATE static_languages SET lg_name_fa='گالیسیایی',lg_iso_2='GL' WHERE lg_iso_2='GL';
UPDATE static_languages SET lg_name_fa='گیلی اسکاتلندی',lg_iso_2='GD' WHERE lg_iso_2='GD';
UPDATE static_languages SET lg_name_fa='مانی',lg_iso_2='GV' WHERE lg_iso_2='GV';
UPDATE static_languages SET lg_name_fa='گرجی',lg_iso_2='KA' WHERE lg_iso_2='KA';
UPDATE static_languages SET lg_name_fa='آلمانی',lg_iso_2='DE' WHERE lg_iso_2='DE';
UPDATE static_languages SET lg_name_fa='یونانی',lg_iso_2='EL' WHERE lg_iso_2='EL';
UPDATE static_languages SET lg_name_fa='گرینلندی',lg_iso_2='KL' WHERE lg_iso_2='KL';
UPDATE static_languages SET lg_name_fa='گوارانی',lg_iso_2='GN' WHERE lg_iso_2='GN';
UPDATE static_languages SET lg_name_fa='گجراتی',lg_iso_2='GU' WHERE lg_iso_2='GU';
UPDATE static_languages SET lg_name_fa='هوسیایی',lg_iso_2='HA' WHERE lg_iso_2='HA';
UPDATE static_languages SET lg_name_fa='عبری',lg_iso_2='HE' WHERE lg_iso_2='HE';
UPDATE static_languages SET lg_name_fa='هندی',lg_iso_2='HI' WHERE lg_iso_2='HI';
UPDATE static_languages SET lg_name_fa='مجاری',lg_iso_2='HU' WHERE lg_iso_2='HU';
UPDATE static_languages SET lg_name_fa='ایسلندی',lg_iso_2='IS' WHERE lg_iso_2='IS';
UPDATE static_languages SET lg_name_fa='اندونزیایی',lg_iso_2='ID' WHERE lg_iso_2='ID';
UPDATE static_languages SET lg_name_fa='میان‌زبان',lg_iso_2='IA' WHERE lg_iso_2='IA';
UPDATE static_languages SET lg_name_fa='اکسیدنتال',lg_iso_2='IE' WHERE lg_iso_2='IE';
UPDATE static_languages SET lg_name_fa='اینوکتیتوت',lg_iso_2='IU' WHERE lg_iso_2='IU';
UPDATE static_languages SET lg_name_fa='اینوپیک',lg_iso_2='IK' WHERE lg_iso_2='IK';
UPDATE static_languages SET lg_name_fa='ایرلندی',lg_iso_2='GA' WHERE lg_iso_2='GA';
UPDATE static_languages SET lg_name_fa='ایتالیایی',lg_iso_2='IT' WHERE lg_iso_2='IT';
UPDATE static_languages SET lg_name_fa='ژاپنی',lg_iso_2='JA' WHERE lg_iso_2='JA';
UPDATE static_languages SET lg_name_fa='کاناده‌ای',lg_iso_2='KN' WHERE lg_iso_2='KN';
UPDATE static_languages SET lg_name_fa='کشمیری',lg_iso_2='KS' WHERE lg_iso_2='KS';
UPDATE static_languages SET lg_name_fa='قزاقی',lg_iso_2='KK' WHERE lg_iso_2='KK';
UPDATE static_languages SET lg_name_fa='کینیارواندایی',lg_iso_2='RW' WHERE lg_iso_2='RW';
UPDATE static_languages SET lg_name_fa='قرقیزی',lg_iso_2='KY' WHERE lg_iso_2='KY';
UPDATE static_languages SET lg_name_fa='روندیایی',lg_iso_2='RN' WHERE lg_iso_2='RN';
UPDATE static_languages SET lg_name_fa='کره‌ای',lg_iso_2='KO' WHERE lg_iso_2='KO';
UPDATE static_languages SET lg_name_fa='کردی',lg_iso_2='KU' WHERE lg_iso_2='KU';
UPDATE static_languages SET lg_name_fa='لائوسی',lg_iso_2='LO' WHERE lg_iso_2='LO';
UPDATE static_languages SET lg_name_fa='لاتینی',lg_iso_2='LA' WHERE lg_iso_2='LA';
UPDATE static_languages SET lg_name_fa='لتونیایی',lg_iso_2='LV' WHERE lg_iso_2='LV';
UPDATE static_languages SET lg_name_fa='لینگالا',lg_iso_2='LN' WHERE lg_iso_2='LN';
UPDATE static_languages SET lg_name_fa='لیتوانیایی',lg_iso_2='LT' WHERE lg_iso_2='LT';
UPDATE static_languages SET lg_name_fa='مقدونی',lg_iso_2='MK' WHERE lg_iso_2='MK';
UPDATE static_languages SET lg_name_fa='مالاگاسیایی',lg_iso_2='MG' WHERE lg_iso_2='MG';
UPDATE static_languages SET lg_name_fa='مالایی',lg_iso_2='MS' WHERE lg_iso_2='MS';
UPDATE static_languages SET lg_name_fa='مالایالامی',lg_iso_2='ML' WHERE lg_iso_2='ML';
UPDATE static_languages SET lg_name_fa='مالتی',lg_iso_2='MT' WHERE lg_iso_2='MT';
UPDATE static_languages SET lg_name_fa='مائوریایی',lg_iso_2='MI' WHERE lg_iso_2='MI';
UPDATE static_languages SET lg_name_fa='مراتی',lg_iso_2='MR' WHERE lg_iso_2='MR';
UPDATE static_languages SET lg_name_fa='مولداویایی',lg_iso_2='MO' WHERE lg_iso_2='MO';
UPDATE static_languages SET lg_name_fa='مغولی',lg_iso_2='MN' WHERE lg_iso_2='MN';
UPDATE static_languages SET lg_name_fa='نائورویی',lg_iso_2='NA' WHERE lg_iso_2='NA';
UPDATE static_languages SET lg_name_fa='نپالی',lg_iso_2='NE' WHERE lg_iso_2='NE';
UPDATE static_languages SET lg_name_fa='نروژی',lg_iso_2='NO' WHERE lg_iso_2='NO';
UPDATE static_languages SET lg_name_fa='اوکیتایی',lg_iso_2='OC' WHERE lg_iso_2='OC';
UPDATE static_languages SET lg_name_fa='اوریه‌ای',lg_iso_2='OR' WHERE lg_iso_2='OR';
UPDATE static_languages SET lg_name_fa='اورومویی',lg_iso_2='OM' WHERE lg_iso_2='OM';
UPDATE static_languages SET lg_name_fa='پختو',lg_iso_2='PS' WHERE lg_iso_2='PS';
UPDATE static_languages SET lg_name_fa='لهستانی',lg_iso_2='PL' WHERE lg_iso_2='PL';
UPDATE static_languages SET lg_name_fa='پرتغالی',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_fa='پنجابی',lg_iso_2='PA' WHERE lg_iso_2='PA';
UPDATE static_languages SET lg_name_fa='کچوایی',lg_iso_2='QU' WHERE lg_iso_2='QU';
UPDATE static_languages SET lg_name_fa='رومانش',lg_iso_2='RM' WHERE lg_iso_2='RM';
UPDATE static_languages SET lg_name_fa='رومانیایی',lg_iso_2='RO' WHERE lg_iso_2='RO';
UPDATE static_languages SET lg_name_fa='روسی',lg_iso_2='RU' WHERE lg_iso_2='RU';
UPDATE static_languages SET lg_name_fa='ساموآیی',lg_iso_2='SM' WHERE lg_iso_2='SM';
UPDATE static_languages SET lg_name_fa='سانگویی',lg_iso_2='SG' WHERE lg_iso_2='SG';
UPDATE static_languages SET lg_name_fa='سنسکریت',lg_iso_2='SA' WHERE lg_iso_2='SA';
UPDATE static_languages SET lg_name_fa='صربی',lg_iso_2='SR' WHERE lg_iso_2='SR';
UPDATE static_languages SET lg_name_fa='سوتویی جنوبی',lg_iso_2='ST' WHERE lg_iso_2='ST';
UPDATE static_languages SET lg_name_fa='تسوانایی',lg_iso_2='TN' WHERE lg_iso_2='TN';
UPDATE static_languages SET lg_name_fa='شونایی',lg_iso_2='SN' WHERE lg_iso_2='SN';
UPDATE static_languages SET lg_name_fa='سندی',lg_iso_2='SD' WHERE lg_iso_2='SD';
UPDATE static_languages SET lg_name_fa='سینهالی',lg_iso_2='SI' WHERE lg_iso_2='SI';
UPDATE static_languages SET lg_name_fa='سوازیایی',lg_iso_2='SS' WHERE lg_iso_2='SS';
UPDATE static_languages SET lg_name_fa='اسلواکی',lg_iso_2='SK' WHERE lg_iso_2='SK';
UPDATE static_languages SET lg_name_fa='اسلووینیایی',lg_iso_2='SL' WHERE lg_iso_2='SL';
UPDATE static_languages SET lg_name_fa='سومالیایی',lg_iso_2='SO' WHERE lg_iso_2='SO';
UPDATE static_languages SET lg_name_fa='اسپانیایی',lg_iso_2='ES' WHERE lg_iso_2='ES';
UPDATE static_languages SET lg_name_fa='سوندایی',lg_iso_2='SU' WHERE lg_iso_2='SU';
UPDATE static_languages SET lg_name_fa='سواحلی',lg_iso_2='SW' WHERE lg_iso_2='SW';
UPDATE static_languages SET lg_name_fa='سوئدی',lg_iso_2='SV' WHERE lg_iso_2='SV';
UPDATE static_languages SET lg_name_fa='تاگالوگی',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_fa='تاجیکی',lg_iso_2='TG' WHERE lg_iso_2='TG';
UPDATE static_languages SET lg_name_fa='تامیلی',lg_iso_2='TA' WHERE lg_iso_2='TA';
UPDATE static_languages SET lg_name_fa='تاتاری',lg_iso_2='TT' WHERE lg_iso_2='TT';
UPDATE static_languages SET lg_name_fa='تلوگویی',lg_iso_2='TE' WHERE lg_iso_2='TE';
UPDATE static_languages SET lg_name_fa='تایلندی',lg_iso_2='TH' WHERE lg_iso_2='TH';
UPDATE static_languages SET lg_name_fa='تبتی',lg_iso_2='BO' WHERE lg_iso_2='BO';
UPDATE static_languages SET lg_name_fa='تیگرینیایی',lg_iso_2='TI' WHERE lg_iso_2='TI';
UPDATE static_languages SET lg_name_fa='تونگایی',lg_iso_2='TO' WHERE lg_iso_2='TO';
UPDATE static_languages SET lg_name_fa='تسونگایی',lg_iso_2='TS' WHERE lg_iso_2='TS';
UPDATE static_languages SET lg_name_fa='ترکی',lg_iso_2='TR' WHERE lg_iso_2='TR';
UPDATE static_languages SET lg_name_fa='ترکمنی',lg_iso_2='TK' WHERE lg_iso_2='TK';
UPDATE static_languages SET lg_name_fa='توی‌یایی',lg_iso_2='TW' WHERE lg_iso_2='TW';
UPDATE static_languages SET lg_name_fa='اویغوری',lg_iso_2='UG' WHERE lg_iso_2='UG';
UPDATE static_languages SET lg_name_fa='اوکراینی',lg_iso_2='UK' WHERE lg_iso_2='UK';
UPDATE static_languages SET lg_name_fa='اردو',lg_iso_2='UR' WHERE lg_iso_2='UR';
UPDATE static_languages SET lg_name_fa='ازبکی',lg_iso_2='UZ' WHERE lg_iso_2='UZ';
UPDATE static_languages SET lg_name_fa='ویتنامی',lg_iso_2='VI' WHERE lg_iso_2='VI';
UPDATE static_languages SET lg_name_fa='ولاپوک',lg_iso_2='VO' WHERE lg_iso_2='VO';
UPDATE static_languages SET lg_name_fa='ویلزی',lg_iso_2='CY' WHERE lg_iso_2='CY';
UPDATE static_languages SET lg_name_fa='ولوفی',lg_iso_2='WO' WHERE lg_iso_2='WO';
UPDATE static_languages SET lg_name_fa='خوسایی',lg_iso_2='XH' WHERE lg_iso_2='XH';
UPDATE static_languages SET lg_name_fa='یدی',lg_iso_2='YI' WHERE lg_iso_2='YI';
UPDATE static_languages SET lg_name_fa='یوروبایی',lg_iso_2='YO' WHERE lg_iso_2='YO';
UPDATE static_languages SET lg_name_fa='زولویی',lg_iso_2='ZU' WHERE lg_iso_2='ZU';
UPDATE static_languages SET lg_name_fa='بوسنیایی',lg_iso_2='BS' WHERE lg_iso_2='BS';
UPDATE static_languages SET lg_name_fa='اوستایی',lg_iso_2='AE' WHERE lg_iso_2='AE';
UPDATE static_languages SET lg_name_fa='آکان',lg_iso_2='AK' WHERE lg_iso_2='AK';
UPDATE static_languages SET lg_name_fa='آراگونی',lg_iso_2='AN' WHERE lg_iso_2='AN';
UPDATE static_languages SET lg_name_fa='آواری',lg_iso_2='AV' WHERE lg_iso_2='AV';
UPDATE static_languages SET lg_name_fa='بامبارایی',lg_iso_2='BM' WHERE lg_iso_2='BM';
UPDATE static_languages SET lg_name_fa='چچنی',lg_iso_2='CE' WHERE lg_iso_2='CE';
UPDATE static_languages SET lg_name_fa='چامورویی',lg_iso_2='CH' WHERE lg_iso_2='CH';
UPDATE static_languages SET lg_name_fa='کریایی',lg_iso_2='CR' WHERE lg_iso_2='CR';
UPDATE static_languages SET lg_name_fa='اسلاوی کلیسایی',lg_iso_2='CU' WHERE lg_iso_2='CU';
UPDATE static_languages SET lg_name_fa='چوواشی',lg_iso_2='CV' WHERE lg_iso_2='CV';
UPDATE static_languages SET lg_name_fa='مالدیوی',lg_iso_2='DV' WHERE lg_iso_2='DV';
UPDATE static_languages SET lg_name_fa='اوه‌ای',lg_iso_2='EE' WHERE lg_iso_2='EE';
UPDATE static_languages SET lg_name_fa='فولایی',lg_iso_2='FF' WHERE lg_iso_2='FF';
UPDATE static_languages SET lg_name_fa='موتویی هیری',lg_iso_2='HO' WHERE lg_iso_2='HO';
UPDATE static_languages SET lg_name_fa='هائیتیایی',lg_iso_2='HT' WHERE lg_iso_2='HT';
UPDATE static_languages SET lg_name_fa='هریرویی',lg_iso_2='HZ' WHERE lg_iso_2='HZ';
UPDATE static_languages SET lg_name_fa='ایگبویی',lg_iso_2='IG' WHERE lg_iso_2='IG';
UPDATE static_languages SET lg_name_fa='یی سیچوان',lg_iso_2='II' WHERE lg_iso_2='II';
UPDATE static_languages SET lg_name_fa='ایدو',lg_iso_2='IO' WHERE lg_iso_2='IO';
UPDATE static_languages SET lg_name_fa='جاوه‌ای',lg_iso_2='JV' WHERE lg_iso_2='JV';
UPDATE static_languages SET lg_name_fa='کنگویی',lg_iso_2='KG' WHERE lg_iso_2='KG';
UPDATE static_languages SET lg_name_fa='کیکویویی',lg_iso_2='KI' WHERE lg_iso_2='KI';
UPDATE static_languages SET lg_name_fa='کوانیاما',lg_iso_2='KJ' WHERE lg_iso_2='KJ';
UPDATE static_languages SET lg_name_fa='کانوریایی',lg_iso_2='KR' WHERE lg_iso_2='KR';
UPDATE static_languages SET lg_name_fa='کومیایی',lg_iso_2='KV' WHERE lg_iso_2='KV';
UPDATE static_languages SET lg_name_fa='کرنوالی',lg_iso_2='KW' WHERE lg_iso_2='KW';
UPDATE static_languages SET lg_name_fa='لوگزامبورگی',lg_iso_2='LB' WHERE lg_iso_2='LB';
UPDATE static_languages SET lg_name_fa='گاندایی',lg_iso_2='LG' WHERE lg_iso_2='LG';
UPDATE static_languages SET lg_name_fa='لیمبورگی',lg_iso_2='LI' WHERE lg_iso_2='LI';
UPDATE static_languages SET lg_name_fa='لوبایی‐کاتانگا',lg_iso_2='LU' WHERE lg_iso_2='LU';
UPDATE static_languages SET lg_name_fa='مارشالی',lg_iso_2='MH' WHERE lg_iso_2='MH';
UPDATE static_languages SET lg_name_fa='بوکسمال نروژی',lg_iso_2='NB' WHERE lg_iso_2='NB';
UPDATE static_languages SET lg_name_fa='انده‌بله‌ای شمالی',lg_iso_2='ND' WHERE lg_iso_2='ND';
UPDATE static_languages SET lg_name_fa='اندونگایی',lg_iso_2='NG' WHERE lg_iso_2='NG';
UPDATE static_languages SET lg_name_fa='نرس جدید نروژی',lg_iso_2='NN' WHERE lg_iso_2='NN';
UPDATE static_languages SET lg_name_fa='انده‌بله‌ای جنوبی',lg_iso_2='NR' WHERE lg_iso_2='NR';
UPDATE static_languages SET lg_name_fa='ناواهویی',lg_iso_2='NV' WHERE lg_iso_2='NV';
UPDATE static_languages SET lg_name_fa='نیانجایی',lg_iso_2='NY' WHERE lg_iso_2='NY';
UPDATE static_languages SET lg_name_fa='اوجیبوایی',lg_iso_2='OJ' WHERE lg_iso_2='OJ';
UPDATE static_languages SET lg_name_fa='آسی',lg_iso_2='OS' WHERE lg_iso_2='OS';
UPDATE static_languages SET lg_name_fa='پالی',lg_iso_2='PI' WHERE lg_iso_2='PI';
UPDATE static_languages SET lg_name_fa='ساردینیایی',lg_iso_2='SC' WHERE lg_iso_2='SC';
UPDATE static_languages SET lg_name_fa='سامی شمالی',lg_iso_2='SE' WHERE lg_iso_2='SE';
UPDATE static_languages SET lg_name_fa='تاهیتیایی',lg_iso_2='TY' WHERE lg_iso_2='TY';
UPDATE static_languages SET lg_name_fa='وندایی',lg_iso_2='VE' WHERE lg_iso_2='VE';
UPDATE static_languages SET lg_name_fa='والونی',lg_iso_2='WA' WHERE lg_iso_2='WA';
UPDATE static_languages SET lg_name_fa='پرتغالی',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_fa='چینی',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_fa='فرانسوی',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_fa='تاگالوگی',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_fa='صرب و کرواتی',lg_iso_2='SH' WHERE lg_iso_2='SH';


